name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Free up space on runner
        run: rm -rf /opt/hostedtoolcache
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.IMAGE_TAG}}
